- README.md
> Ajoute une introduction au chapitre how to use

- README.md
- components/mentions-legales/texte-mentions-legales.jsx
PR d'origine : betagouv/leximpact-client#111
> Migration de beta.gouv.fr vers an.fr 

- components/connexion/config.json
- components/connexion/form/tests/__snapshots__/roles-input.test.jsx.snap
- components/connexion/tests/utils.test.js
Trello : https://trello.com/c/4CMu2OKH/199-connexion-anfr
> Ajouter le domaine @an.fr comme domaine autorisé pour la connexion (front)

- components/articles/article-alinea-2/article-alinea-2-component.jsx
- components/articles/article-tranches/bouton-ajouter-tranche.jsx
- components/articles/article-tranches/bouton-ajouter-tranche.module.scss
- components/articles/article-tranches/bouton-supprimer-tranche.jsx
- components/articles/article-tranches/bouton-supprimer-tranche.module.scss
Carte trello : https://trello.com/c/54J3uN6A/214-changer-la-couleur-des-boutons-ajouter-suppr-une-tranche
> Mettre les boutons "ajouter" et "suppression" de tranches de la bonne couleur

- components/app-header/app-header-component.jsx
- components/app-header/login-button-mobile.jsx
- components/app-header/login-button.jsx
- components/app-header/tests/__snapshots__/app-header-component.test.jsx.snap
- components/app-header/tests/__snapshots__/login-button.test.jsx.snap
- package-lock.json
- package.json
- redux/actions/index.js
- redux/actions/log-out.js
Trello : https://trello.com/c/B8x8mZvf/194-ajouter-un-bouton-logout
@DorineLam j'ai pris la liberté de choisir l'icône de déconnexion. Dis-moi si elle te convient et, sinon, n'hésite pas à m'en suggérer une autre.
> Permettre aux utilisateurs de se déconnecter

- components/app-header/app-header-component.jsx
- components/app-header/tests/__snapshots__/app-header-component.test.jsx.snap
- components/articles/articles-component.jsx
- components/reformeur/reformeur-component.jsx
- components/reformeur/reformeur-component.module.scss
- components/simulation-menu/simulation-menubar-component.jsx
- pages/index.jsx
- pages/index.module.scss
- styles/index.scss
Trello : https://trello.com/c/9d9abszx/145-article-scroller-%C3%A0-lint%C3%A9rieur-du-paper
> Ajouter des barres de défilement dans les panneaux paramètres et résultats

- components/articles/article-alinea-2/article-alinea-2-component.jsx
- components/articles/article-alinea-3/article-alinea-3-component.jsx
- components/articles/article-alinea-4a/article-alinea-4a-component.jsx
- components/articles/articles-component.jsx
- components/articles/articles-component.module.scss
- components/articles/articles.module.scss
Trello : https://trello.com/c/x9K2BSq7/226-r%C3%A9soudre-le-dernier-warning
> Supprimer les dernières alertes React en développement

- components/cartes-impact/impact-component.jsx
- components/cartes-impact/impact-component.module.scss
- components/reformeur/reformeur-component.module.scss
Trello : https://trello.com/c/doMIE0iu/248-barre-de-simu-fixe
> Rendre fixe la barre de simulation

- .github/contributing.md
Précédemment approuvées ici : https://trello.com/c/zq4y1Zxu/261-proposition-conventions-de-nommage-front
> Ajouter les règles de codage

- redux/reducers/results/cas-types.js
Nécessaire pour fusionner https://github.com/leximpact/leximpact-server/pull/20
> Supprimer le traitement de la propriété "wprm" de la réponse du serveur

- components/dotations/articles/Articles.tsx
- components/dotations/results/commune-summary/CommuneSummary.tsx
https://trello.com/c/wjcHC3KF/350-changer-la-position-du-panneau-montant-des-dotations
> Modifier l'ordre des panneaux dans les articles des dotations

- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.module.scss
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.tsx
- redux/reducers/descriptions/dotations/strates.ts
https://trello.com/c/c0N3RRlY/355-mettre-les-bonnes-strates
> Update strates and add scrolls

- components/common/card/Card.module.scss
- components/common/card/Card.tsx
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.tsx
- components/dotations/results/commune-type/CommuneType.module.scss
- components/dotations/results/commune-type/CommuneType.tsx
- components/dotations/results/commune-type/dotation-par-hab/DotationParHab.tsx
- components/dotations/results/commune-type/habitant-label/HabitantLabel.tsx
- components/dotations/results/commune-type/potentiel-financier/PotentielFinancier.module.scss
- components/dotations/results/commune-type/potentiel-financier/PotentielFinancier.tsx
- components/ir/cartes-impact/gagnants-perdants/GagnantsPerdantsContent/GagnantsPerdantsContent.module.scss
- components/ir/cartes-impact/simple-card/impact-impots.jsx
- components/ir/cartes-impact/simple-card/impact-impots.module.scss
- components/ir/cartes-impact/simple-card/simple-card-component.jsx
- pages/dotations.tsx
- styles/_variables.scss
https://trello.com/c/uj121U0V/371-ajouter-les-euros-dans-le-tableau-arrondir-sans-d%C3%A9cimales
https://trello.com/c/ykGiR2Mt/374-potentiel-financier-ui-comme-ir
> Améliorer l'UI dotations

- components/dotations/articles/Articles.tsx
- redux/actions/popin-cas-types-add.js
- redux/actions/popin-cas-types-edit.js
- redux/actions/popin-logout.js
- redux/actions/popin-show-connexion.js
- redux/actions/tests/popin-cas-types-add.js
- redux/actions/tests/popin-show-connexion.test.js
- Afficher uniquement la DSU si présence de `?dsu` dans l'URL.
- Régler bug d'affichage des popin.
> Add DSU query param

- components/dotations/results/Results.tsx
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.module.scss
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.tsx
- components/dotations/results/commune-summary/CommuneSummary.tsx
- redux/actions/simulations/simulate-dotations.ts
- redux/reducers/results/index.ts
- redux/reducers/results/interfaces/dotations-diff-state.ts
- redux/reducers/results/interfaces/dotations-state.ts
https://trello.com/c/CeKrdsg9/391-carte-%C3%A9ligibilit%C3%A9-communes-dsr-dsu
https://trello.com/c/ZGWkRKPb/390-nouveau-tableur-dsr-dsu
> Afficher les résultats de la DSU dans la carte "résumé" et dans le tableau de détails

- components/common/articles-inputs/values/Values.tsx
- components/common/articles-inputs/values/number-input/NumberInput.tsx
- components/dotations/articles/dsr-fraction-bourg-centre/DsrFractionBourgCentre.tsx
- components/dotations/articles/dsu-eligibilite/DsuEligibilite.module.scss
- components/dotations/articles/dsu-eligibilite/DsuEligibilite.tsx
- components/dotations/articles/dsu-repartition/DsuRepartition.module.scss
- components/dotations/articles/dsu-repartition/DsuRepartition.tsx
- components/ir/articles/quotient-familial/regles-generales/QfTable.module.scss
- components/ir/articles/quotient-familial/regles-generales/QfTable.tsx
Trello : https://trello.com/c/rIC1w8E8/367-quand-je-modifie-un-champs-et-que-je-clique-sur-entr%C3%A9e-la-simulation-doit-se-d%C3%A9clencher-difficult%C3%A9-pas-d%C3%A9clencher-et-ir-et-dotat
-> Quand je modifie un champs et que je clique sur Entrée, la simulation doit se déclencher. 
Trello : https://trello.com/c/2oie0Fu7/376-nombre-entier-cas-type-potentiel-financier-2-d%C3%A9cimales-tableur
-> Bon affichage et utilisation des `le double [ x 2 fois ]`
> Petites améliorations

- components/dotations/results/common/index.ts
- components/dotations/results/common/trend-arrow/TrendArrow.module.scss
- components/dotations/results/common/trend-arrow/TrendArrow.tsx
- components/dotations/results/common/trend-arrow/index.ts
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.tsx
- components/dotations/results/commune-type/CommuneType.module.scss
- components/dotations/results/commune-type/CommuneType.tsx
- components/dotations/results/commune-type/dotation-diff/DotationDiff.tsx
- components/dotations/results/commune-type/dotation-trend/DotationTrend.module.scss
- components/dotations/results/commune-type/dotation-trend/DotationTrend.tsx
- components/dotations/results/commune-type/dotation-trend/index.ts
- public/icons/picto-dotation-tendance-baisse.svg
- public/icons/picto-dotation-tendance-monte.svg
- redux/reducers/results/baseToAmendement/dotations.ts
- redux/reducers/results/baseToPlf/dotations.ts
- redux/reducers/results/interfaces/dotations-diff-state.ts
- redux/reducers/results/interfaces/dotations-state.ts
https://trello.com/c/kzr3ivoS/395-ajouter-la-fl%C3%A8che-dans-la-carte-commune-type-et-la-carte-tableau
Quelques remarques :
- Concernant le nom donné à une dotation stable, je suis allé voir la définition de "tendance". La tendance fait référence à une _évolution_, ce qui n'est pas le cas ici. J'ai donc mis "Pas d'évolution" à la place.
- Lorsqu'il n'y a pas d'évolution, j'ai laissé un petit tiret (plus discret). Qu'en penses-tu ?
> Ajouter les flèches de tendances aux communes types et au tableau

- components/common/articles-inputs/values/Values.module.scss
- components/common/articles-inputs/values/Values.tsx
- components/common/simulation-page/simulation-menu/legende/Legende.tsx
- components/dotations/articles/montant-dgf/MontantDgf.tsx
- components/dotations/results/commune-summary/CommuneSummary.tsx
- redux/reducers/parameters/plf/index.ts
- redux/reducers/results/baseToPlf/dotations.ts
- redux/reducers/results/plf/dotations.ts
https://trello.com/c/W873wrL0/354-mettre-en-place-le-nouvel-affichage-des-nombres-base-plf-amendement
> Afficher le PLF comme correction du code existant et l'amendement comme une correction du PLF (ou existant)

- components/common/articles-inputs/values/Values.tsx
- components/dotations/articles/montant-dsr-dsu/MontantDsrDsu.tsx
- components/dotations/results/commune-type/eligibilite/Eligibilite.tsx
Trello : https://trello.com/c/MZkNj3CY/402-enlever-paragraphe-caduc-sur-la-partie-de-larticle-montants-dsr-dsu-qui-commence-par-%C3%A0-compter-de-2012
Trello : https://trello.com/c/a7j7BvdT/346-corriger-hack-%C3%A9ligible-string-au-lieu-de-numbers
> Corriger bug "éligible0" et enlever le "caduc" d'une partie du code

- components/dotations/articles/Articles.tsx
- components/dotations/articles/dsu-eligibilite/DsuEligibilite.tsx
- components/dotations/results/Results.tsx
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.module.scss
- components/dotations/results/commune-strate-details/commune-strate-details-table/CommuneStrateDetailsTable.tsx
- components/dotations/results/commune-type/CommuneType.tsx
- redux/actions/simulations/simulate-dotations.ts
- redux/reducers/parameters/base/dotations.ts
- redux/reducers/parameters/plf/dotations.ts
https://trello.com/c/pjfsi2is/400-v%C3%A9rifier-que-laffiche-dsu-affiche-bien-les-valeurs-dsu-et-non-dsr-v%C3%A9rifier-le-calcul-des-diff%C3%A9rences
Cette PR nécessite que https://github.com/leximpact/leximpact-server/pull/31 soit fusionnée.
> Activer la DSU

- components/dotations/results/commune-type/CommuneType.tsx
- components/dotations/results/commune-type/dotation-a-terme/DotationATerme.module.scss
- components/dotations/results/commune-type/dotation-a-terme/DotationATerme.tsx
- components/dotations/results/commune-type/dotation-a-terme/index.ts
- components/dotations/results/commune-type/dotation-par-hab/DotationParHab.tsx
- redux/actions/simulations/simulate-dotations.ts
- redux/reducers/descriptions/dotations/communes-types.ts
- redux/reducers/results/interfaces/dotations-state.ts
Trello : https://trello.com/c/2p5lbwQX/397-ajouter-le-montant-de-lann%C3%A9e-prochaine-de-la-dsr
Comme la partie serveur n'est pas implémentée, on ne voit donc rien :
> Distingue le montant à terme de la DSR

- components/common/articles-inputs/values/Values.tsx
- components/dotations/results/commune-type/dotation-a-terme/DotationATerme.tsx
- components/dotations/results/commune-type/dotation-par-hab/DotationParHab.tsx
https://trello.com/c/QnKnvlO0/434-affichage-des-arrondis
> Régler les problèmes d'arrondi

- pages/dotations.tsx
- redux/actions/descriptions/dotations/index.ts
- redux/actions/descriptions/dotations/init-communes-types.ts
- redux/actions/index.ts
- redux/reducers/descriptions/dotations/communes-types.ts
- redux/reducers/display.ts
https://trello.com/c/WzF9z24O/453-enregistrer-mes-communes-pr%C3%A9f%C3%A9r%C3%A9es-dune-session-%C3%A0-une-autre
1. J'ouvre la page, j'ai des communes par défaut.
2. J'ajoute une commune et je rafraîchis la page. La commune est toujours là.
3. Je supprime la commune et je rafraîchis la page. La commune n'est plus là.
> Enregistrer les communes types

- components/dotations/help-windows/df-montant-help-window/DfMontantHelpWindow.module.scss
- components/dotations/help-windows/df-montant-help-window/DfMontantHelpWindow.tsx
- components/dotations/results/commune-type/CommuneType.tsx
https://trello.com/c/iq0mNuQz/463-panneaux-daide-df
> Add DF warning on montants

- README.md
- components/presentation-cgu/texte-presentation-generale.tsx
- package.json
- Changement de l'url des github de betagouv vers leximpact
- Mise a jour de l'adresse mail
> Change to new url and mail of Leximpact

- components/mentions-legales/texte-mentions-legales.tsx
Suite au changement d"hébergeur, Changement de l'adresse postale de l'hebergeur
Déployé pour test sur https://leximpactclient-integ.leximpact.dev/mentions-legales
> Changement de l'adresse postale de l'hebergeur
